// Todos los municipios de Colombia (fuente: DANE)
export interface CiudadEntry {
  ciudad: string;
  departamento: string;
}

export const DEPARTAMENTOS = [
  "Amazonas",
  "Antioquia",
  "Arauca",
  "San Andrés y Providencia",
  "Atlántico",
  "Bogotá D.C.",
  "Bolívar",
  "Boyacá",
  "Caldas",
  "Caquetá",
  "Casanare",
  "Cauca",
  "Cesar",
  "Chocó",
  "Cundinamarca",
  "Córdoba",
  "Guainía",
  "Guaviare",
  "Huila",
  "La Guajira",
  "Magdalena",
  "Meta",
  "Nariño",
  "Norte de Santander",
  "Putumayo",
  "Quindío",
  "Risaralda",
  "Santander",
  "Sucre",
  "Tolima",
  "Valle del Cauca",
  "Vaupés",
  "Vichada",
];

export const CIUDADES: CiudadEntry[] = [
  { ciudad: "El Encanto", departamento: "Amazonas" },
  { ciudad: "La Chorrera", departamento: "Amazonas" },
  { ciudad: "La Pedrera", departamento: "Amazonas" },
  { ciudad: "La Victoria", departamento: "Amazonas" },
  { ciudad: "Leticia", departamento: "Amazonas" },
  { ciudad: "Miriti - Paraná", departamento: "Amazonas" },
  { ciudad: "Puerto Alegria", departamento: "Amazonas" },
  { ciudad: "Puerto Arica", departamento: "Amazonas" },
  { ciudad: "Puerto Nariño", departamento: "Amazonas" },
  { ciudad: "Puerto Santander", departamento: "Amazonas" },
  { ciudad: "Tarapacá", departamento: "Amazonas" },
  { ciudad: "Abejorral", departamento: "Antioquia" },
  { ciudad: "Abriaquí", departamento: "Antioquia" },
  { ciudad: "Alejandría", departamento: "Antioquia" },
  { ciudad: "Amaga", departamento: "Antioquia" },
  { ciudad: "Amalfi", departamento: "Antioquia" },
  { ciudad: "Andes", departamento: "Antioquia" },
  { ciudad: "Angelopolis", departamento: "Antioquia" },
  { ciudad: "Angostura", departamento: "Antioquia" },
  { ciudad: "Anorí", departamento: "Antioquia" },
  { ciudad: "Anza", departamento: "Antioquia" },
  { ciudad: "Apartadó", departamento: "Antioquia" },
  { ciudad: "Arboletes", departamento: "Antioquia" },
  { ciudad: "Argelia", departamento: "Antioquia" },
  { ciudad: "Armenia", departamento: "Antioquia" },
  { ciudad: "Barbosa", departamento: "Antioquia" },
  { ciudad: "Bello", departamento: "Antioquia" },
  { ciudad: "Belmira", departamento: "Antioquia" },
  { ciudad: "Betania", departamento: "Antioquia" },
  { ciudad: "Betulia", departamento: "Antioquia" },
  { ciudad: "Briceño", departamento: "Antioquia" },
  { ciudad: "Buriticá", departamento: "Antioquia" },
  { ciudad: "Cáceres", departamento: "Antioquia" },
  { ciudad: "Caicedo", departamento: "Antioquia" },
  { ciudad: "Caldas", departamento: "Antioquia" },
  { ciudad: "Campamento", departamento: "Antioquia" },
  { ciudad: "Cañasgordas", departamento: "Antioquia" },
  { ciudad: "Caracolí", departamento: "Antioquia" },
  { ciudad: "Caramanta", departamento: "Antioquia" },
  { ciudad: "Carepa", departamento: "Antioquia" },
  { ciudad: "Carmen De Viboral", departamento: "Antioquia" },
  { ciudad: "Carolina", departamento: "Antioquia" },
  { ciudad: "Caucasia", departamento: "Antioquia" },
  { ciudad: "Chigorodó", departamento: "Antioquia" },
  { ciudad: "Cisneros", departamento: "Antioquia" },
  { ciudad: "Ciudad Bolívar", departamento: "Antioquia" },
  { ciudad: "Cocorná", departamento: "Antioquia" },
  { ciudad: "Concepción", departamento: "Antioquia" },
  { ciudad: "Concordia", departamento: "Antioquia" },
  { ciudad: "Copacabana", departamento: "Antioquia" },
  { ciudad: "Dabeiba", departamento: "Antioquia" },
  { ciudad: "Don Matias", departamento: "Antioquia" },
  { ciudad: "Ebéjico", departamento: "Antioquia" },
  { ciudad: "El Bagre", departamento: "Antioquia" },
  { ciudad: "Entrerrios", departamento: "Antioquia" },
  { ciudad: "Envigado", departamento: "Antioquia" },
  { ciudad: "Fredonia", departamento: "Antioquia" },
  { ciudad: "Frontino", departamento: "Antioquia" },
  { ciudad: "Giraldo", departamento: "Antioquia" },
  { ciudad: "Girardota", departamento: "Antioquia" },
  { ciudad: "Gómez Plata", departamento: "Antioquia" },
  { ciudad: "Granada", departamento: "Antioquia" },
  { ciudad: "Guadalupe", departamento: "Antioquia" },
  { ciudad: "Guarne", departamento: "Antioquia" },
  { ciudad: "Guatape", departamento: "Antioquia" },
  { ciudad: "Heliconia", departamento: "Antioquia" },
  { ciudad: "Hispania", departamento: "Antioquia" },
  { ciudad: "Itagui", departamento: "Antioquia" },
  { ciudad: "Ituango", departamento: "Antioquia" },
  { ciudad: "Jardín", departamento: "Antioquia" },
  { ciudad: "Jericó", departamento: "Antioquia" },
  { ciudad: "La Ceja", departamento: "Antioquia" },
  { ciudad: "La Estrella", departamento: "Antioquia" },
  { ciudad: "La Pintada", departamento: "Antioquia" },
  { ciudad: "La Unión", departamento: "Antioquia" },
  { ciudad: "Liborina", departamento: "Antioquia" },
  { ciudad: "Maceo", departamento: "Antioquia" },
  { ciudad: "Marinilla", departamento: "Antioquia" },
  { ciudad: "Medellín", departamento: "Antioquia" },
  { ciudad: "Montebello", departamento: "Antioquia" },
  { ciudad: "Murindó", departamento: "Antioquia" },
  { ciudad: "Mutata", departamento: "Antioquia" },
  { ciudad: "Nariño", departamento: "Antioquia" },
  { ciudad: "Nechí", departamento: "Antioquia" },
  { ciudad: "Necoclí", departamento: "Antioquia" },
  { ciudad: "Olaya", departamento: "Antioquia" },
  { ciudad: "Peñol", departamento: "Antioquia" },
  { ciudad: "Peque", departamento: "Antioquia" },
  { ciudad: "Pueblorrico", departamento: "Antioquia" },
  { ciudad: "Puerto Berrio", departamento: "Antioquia" },
  { ciudad: "Puerto Nare", departamento: "Antioquia" },
  { ciudad: "Puerto Triunfo", departamento: "Antioquia" },
  { ciudad: "Remedios", departamento: "Antioquia" },
  { ciudad: "Retiro", departamento: "Antioquia" },
  { ciudad: "Rionegro", departamento: "Antioquia" },
  { ciudad: "Sabanalarga", departamento: "Antioquia" },
  { ciudad: "Sabaneta", departamento: "Antioquia" },
  { ciudad: "Salgar", departamento: "Antioquia" },
  { ciudad: "San Andrés", departamento: "Antioquia" },
  { ciudad: "San Carlos", departamento: "Antioquia" },
  { ciudad: "San Francisco", departamento: "Antioquia" },
  { ciudad: "San Jerónimo", departamento: "Antioquia" },
  { ciudad: "San José De La Montaña", departamento: "Antioquia" },
  { ciudad: "San Juan De Uraba", departamento: "Antioquia" },
  { ciudad: "San Luis", departamento: "Antioquia" },
  { ciudad: "San Pedro", departamento: "Antioquia" },
  { ciudad: "San Pedro De Uraba", departamento: "Antioquia" },
  { ciudad: "San Rafael", departamento: "Antioquia" },
  { ciudad: "San Roque", departamento: "Antioquia" },
  { ciudad: "San Vicente", departamento: "Antioquia" },
  { ciudad: "Santa Barbara", departamento: "Antioquia" },
  { ciudad: "Santa Rosa De Osos", departamento: "Antioquia" },
  { ciudad: "Santafé De Antioquia", departamento: "Antioquia" },
  { ciudad: "Santo Domingo", departamento: "Antioquia" },
  { ciudad: "Santuario", departamento: "Antioquia" },
  { ciudad: "Segovia", departamento: "Antioquia" },
  { ciudad: "Sonson", departamento: "Antioquia" },
  { ciudad: "Sopetran", departamento: "Antioquia" },
  { ciudad: "Támesis", departamento: "Antioquia" },
  { ciudad: "Tarazá", departamento: "Antioquia" },
  { ciudad: "Tarso", departamento: "Antioquia" },
  { ciudad: "Titiribí", departamento: "Antioquia" },
  { ciudad: "Toledo", departamento: "Antioquia" },
  { ciudad: "Turbo", departamento: "Antioquia" },
  { ciudad: "Uramita", departamento: "Antioquia" },
  { ciudad: "Urrao", departamento: "Antioquia" },
  { ciudad: "Valdivia", departamento: "Antioquia" },
  { ciudad: "Valparaiso", departamento: "Antioquia" },
  { ciudad: "Vegachí", departamento: "Antioquia" },
  { ciudad: "Venecia", departamento: "Antioquia" },
  { ciudad: "Vigía Del Fuerte", departamento: "Antioquia" },
  { ciudad: "Yalí", departamento: "Antioquia" },
  { ciudad: "Yarumal", departamento: "Antioquia" },
  { ciudad: "Yolombó", departamento: "Antioquia" },
  { ciudad: "Yondó", departamento: "Antioquia" },
  { ciudad: "Zaragoza", departamento: "Antioquia" },
  { ciudad: "Arauca", departamento: "Arauca" },
  { ciudad: "Arauquita", departamento: "Arauca" },
  { ciudad: "Cravo Norte", departamento: "Arauca" },
  { ciudad: "Fortul", departamento: "Arauca" },
  { ciudad: "Puerto Rondón", departamento: "Arauca" },
  { ciudad: "Saravena", departamento: "Arauca" },
  { ciudad: "Tame", departamento: "Arauca" },
  { ciudad: "Providencia Y Santa Catalina", departamento: "San Andrés y Providencia" },
  { ciudad: "San Andres", departamento: "San Andrés y Providencia" },
  { ciudad: "Baranoa", departamento: "Atlántico" },
  { ciudad: "Barranquilla", departamento: "Atlántico" },
  { ciudad: "Campo De La Cruz", departamento: "Atlántico" },
  { ciudad: "Candelaria", departamento: "Atlántico" },
  { ciudad: "Galapa", departamento: "Atlántico" },
  { ciudad: "Juan De Acosta", departamento: "Atlántico" },
  { ciudad: "Luruaco", departamento: "Atlántico" },
  { ciudad: "Malambo", departamento: "Atlántico" },
  { ciudad: "Manati", departamento: "Atlántico" },
  { ciudad: "Palmar De Varela", departamento: "Atlántico" },
  { ciudad: "Piojó", departamento: "Atlántico" },
  { ciudad: "Polonuevo", departamento: "Atlántico" },
  { ciudad: "Ponedera", departamento: "Atlántico" },
  { ciudad: "Puerto Colombia", departamento: "Atlántico" },
  { ciudad: "Repelon", departamento: "Atlántico" },
  { ciudad: "Sabanagrande", departamento: "Atlántico" },
  { ciudad: "Sabanalarga", departamento: "Atlántico" },
  { ciudad: "Santa Lucia", departamento: "Atlántico" },
  { ciudad: "Santo Tomas", departamento: "Atlántico" },
  { ciudad: "Soledad", departamento: "Atlántico" },
  { ciudad: "Suan", departamento: "Atlántico" },
  { ciudad: "Tubara", departamento: "Atlántico" },
  { ciudad: "Usiacuri", departamento: "Atlántico" },
  { ciudad: "Bogota D.C.", departamento: "Bogotá D.C." },
  { ciudad: "Achí", departamento: "Bolívar" },
  { ciudad: "Altos Del Rosario", departamento: "Bolívar" },
  { ciudad: "Arenal", departamento: "Bolívar" },
  { ciudad: "Arjona", departamento: "Bolívar" },
  { ciudad: "Arroyohondo", departamento: "Bolívar" },
  { ciudad: "Barranco De Loba", departamento: "Bolívar" },
  { ciudad: "Calamar", departamento: "Bolívar" },
  { ciudad: "Cantagallo", departamento: "Bolívar" },
  { ciudad: "Carmen De Bolívar", departamento: "Bolívar" },
  { ciudad: "Cartagena", departamento: "Bolívar" },
  { ciudad: "Cicuco", departamento: "Bolívar" },
  { ciudad: "Clemencia", departamento: "Bolívar" },
  { ciudad: "Córdoba", departamento: "Bolívar" },
  { ciudad: "El Guamo", departamento: "Bolívar" },
  { ciudad: "El Peñon", departamento: "Bolívar" },
  { ciudad: "Hatillo De Loba", departamento: "Bolívar" },
  { ciudad: "Magangué", departamento: "Bolívar" },
  { ciudad: "Mahates", departamento: "Bolívar" },
  { ciudad: "Margarita", departamento: "Bolívar" },
  { ciudad: "María La Baja", departamento: "Bolívar" },
  { ciudad: "Mompós", departamento: "Bolívar" },
  { ciudad: "Montecristo", departamento: "Bolívar" },
  { ciudad: "Morales", departamento: "Bolívar" },
  { ciudad: "Pinillos", departamento: "Bolívar" },
  { ciudad: "Regidor", departamento: "Bolívar" },
  { ciudad: "Río Viejo", departamento: "Bolívar" },
  { ciudad: "San Cristobal", departamento: "Bolívar" },
  { ciudad: "San Estanislao", departamento: "Bolívar" },
  { ciudad: "San Fernando", departamento: "Bolívar" },
  { ciudad: "San Jacinto", departamento: "Bolívar" },
  { ciudad: "San Jacinto Del Cauca", departamento: "Bolívar" },
  { ciudad: "San Juan Nepomuceno", departamento: "Bolívar" },
  { ciudad: "San Martin De Loba", departamento: "Bolívar" },
  { ciudad: "San Pablo", departamento: "Bolívar" },
  { ciudad: "Santa Catalina", departamento: "Bolívar" },
  { ciudad: "Santa Rosa De Lima", departamento: "Bolívar" },
  { ciudad: "Santa Rosa Del Sur", departamento: "Bolívar" },
  { ciudad: "Simití", departamento: "Bolívar" },
  { ciudad: "Soplaviento", departamento: "Bolívar" },
  { ciudad: "Talaigua Nuevo", departamento: "Bolívar" },
  { ciudad: "Tiquisio", departamento: "Bolívar" },
  { ciudad: "Turbaco", departamento: "Bolívar" },
  { ciudad: "Turbana", departamento: "Bolívar" },
  { ciudad: "Villanueva", departamento: "Bolívar" },
  { ciudad: "Zambrano", departamento: "Bolívar" },
  { ciudad: "Almeida", departamento: "Boyacá" },
  { ciudad: "Aquitania", departamento: "Boyacá" },
  { ciudad: "Arcabuco", departamento: "Boyacá" },
  { ciudad: "Belén", departamento: "Boyacá" },
  { ciudad: "Berbeo", departamento: "Boyacá" },
  { ciudad: "Betéitiva", departamento: "Boyacá" },
  { ciudad: "Boavita", departamento: "Boyacá" },
  { ciudad: "Boyacá", departamento: "Boyacá" },
  { ciudad: "Briceño", departamento: "Boyacá" },
  { ciudad: "Buenavista", departamento: "Boyacá" },
  { ciudad: "Busbanzá", departamento: "Boyacá" },
  { ciudad: "Caldas", departamento: "Boyacá" },
  { ciudad: "Campohermoso", departamento: "Boyacá" },
  { ciudad: "Cerinza", departamento: "Boyacá" },
  { ciudad: "Chinavita", departamento: "Boyacá" },
  { ciudad: "Chiquinquirá", departamento: "Boyacá" },
  { ciudad: "Chíquiza", departamento: "Boyacá" },
  { ciudad: "Chiscas", departamento: "Boyacá" },
  { ciudad: "Chita", departamento: "Boyacá" },
  { ciudad: "Chitaraque", departamento: "Boyacá" },
  { ciudad: "Chivatá", departamento: "Boyacá" },
  { ciudad: "Chivor", departamento: "Boyacá" },
  { ciudad: "Ciénega", departamento: "Boyacá" },
  { ciudad: "Cómbita", departamento: "Boyacá" },
  { ciudad: "Coper", departamento: "Boyacá" },
  { ciudad: "Corrales", departamento: "Boyacá" },
  { ciudad: "Covarachía", departamento: "Boyacá" },
  { ciudad: "Cubará", departamento: "Boyacá" },
  { ciudad: "Cucaita", departamento: "Boyacá" },
  { ciudad: "Cuítiva", departamento: "Boyacá" },
  { ciudad: "Duitama", departamento: "Boyacá" },
  { ciudad: "El Cocuy", departamento: "Boyacá" },
  { ciudad: "El Espino", departamento: "Boyacá" },
  { ciudad: "Firavitoba", departamento: "Boyacá" },
  { ciudad: "Floresta", departamento: "Boyacá" },
  { ciudad: "Gachantivá", departamento: "Boyacá" },
  { ciudad: "Gameza", departamento: "Boyacá" },
  { ciudad: "Garagoa", departamento: "Boyacá" },
  { ciudad: "Guacamayas", departamento: "Boyacá" },
  { ciudad: "Guateque", departamento: "Boyacá" },
  { ciudad: "Guayatá", departamento: "Boyacá" },
  { ciudad: "Güicán", departamento: "Boyacá" },
  { ciudad: "Iza", departamento: "Boyacá" },
  { ciudad: "Jenesano", departamento: "Boyacá" },
  { ciudad: "Jericó", departamento: "Boyacá" },
  { ciudad: "La Capilla", departamento: "Boyacá" },
  { ciudad: "La Uvita", departamento: "Boyacá" },
  { ciudad: "La Victoria", departamento: "Boyacá" },
  { ciudad: "Labranzagrande", departamento: "Boyacá" },
  { ciudad: "Macanal", departamento: "Boyacá" },
  { ciudad: "Maripí", departamento: "Boyacá" },
  { ciudad: "Miraflores", departamento: "Boyacá" },
  { ciudad: "Mongua", departamento: "Boyacá" },
  { ciudad: "Monguí", departamento: "Boyacá" },
  { ciudad: "Moniquirá", departamento: "Boyacá" },
  { ciudad: "Motavita", departamento: "Boyacá" },
  { ciudad: "Muzo", departamento: "Boyacá" },
  { ciudad: "Nobsa", departamento: "Boyacá" },
  { ciudad: "Nuevo Colón", departamento: "Boyacá" },
  { ciudad: "Oicatá", departamento: "Boyacá" },
  { ciudad: "Otanche", departamento: "Boyacá" },
  { ciudad: "Pachavita", departamento: "Boyacá" },
  { ciudad: "Páez", departamento: "Boyacá" },
  { ciudad: "Paipa", departamento: "Boyacá" },
  { ciudad: "Pajarito", departamento: "Boyacá" },
  { ciudad: "Panqueba", departamento: "Boyacá" },
  { ciudad: "Pauna", departamento: "Boyacá" },
  { ciudad: "Paya", departamento: "Boyacá" },
  { ciudad: "Paz De Río", departamento: "Boyacá" },
  { ciudad: "Pesca", departamento: "Boyacá" },
  { ciudad: "Pisba", departamento: "Boyacá" },
  { ciudad: "Puerto Boyaca", departamento: "Boyacá" },
  { ciudad: "Quípama", departamento: "Boyacá" },
  { ciudad: "Ramiriquí", departamento: "Boyacá" },
  { ciudad: "Ráquira", departamento: "Boyacá" },
  { ciudad: "Rondón", departamento: "Boyacá" },
  { ciudad: "Saboyá", departamento: "Boyacá" },
  { ciudad: "Sáchica", departamento: "Boyacá" },
  { ciudad: "Samacá", departamento: "Boyacá" },
  { ciudad: "San Eduardo", departamento: "Boyacá" },
  { ciudad: "San José De Pare", departamento: "Boyacá" },
  { ciudad: "San Luis De Gaceno", departamento: "Boyacá" },
  { ciudad: "San Mateo", departamento: "Boyacá" },
  { ciudad: "San Miguel De Sema", departamento: "Boyacá" },
  { ciudad: "San Pablo Borbur", departamento: "Boyacá" },
  { ciudad: "San Rosa Viterbo", departamento: "Boyacá" },
  { ciudad: "Santa María", departamento: "Boyacá" },
  { ciudad: "Santa Sofía", departamento: "Boyacá" },
  { ciudad: "Santana", departamento: "Boyacá" },
  { ciudad: "Sativanorte", departamento: "Boyacá" },
  { ciudad: "Sativasur", departamento: "Boyacá" },
  { ciudad: "Siachoque", departamento: "Boyacá" },
  { ciudad: "Soatá", departamento: "Boyacá" },
  { ciudad: "Socha", departamento: "Boyacá" },
  { ciudad: "Socotá", departamento: "Boyacá" },
  { ciudad: "Sogamoso", departamento: "Boyacá" },
  { ciudad: "Somondoco", departamento: "Boyacá" },
  { ciudad: "Sora", departamento: "Boyacá" },
  { ciudad: "Soracá", departamento: "Boyacá" },
  { ciudad: "Sotaquirá", departamento: "Boyacá" },
  { ciudad: "Susacón", departamento: "Boyacá" },
  { ciudad: "Sutamarchán", departamento: "Boyacá" },
  { ciudad: "Sutatenza", departamento: "Boyacá" },
  { ciudad: "Tasco", departamento: "Boyacá" },
  { ciudad: "Tenza", departamento: "Boyacá" },
  { ciudad: "Tibaná", departamento: "Boyacá" },
  { ciudad: "Tibasosa", departamento: "Boyacá" },
  { ciudad: "Tinjacá", departamento: "Boyacá" },
  { ciudad: "Tipacoque", departamento: "Boyacá" },
  { ciudad: "Toca", departamento: "Boyacá" },
  { ciudad: "Togüí", departamento: "Boyacá" },
  { ciudad: "Tópaga", departamento: "Boyacá" },
  { ciudad: "Tota", departamento: "Boyacá" },
  { ciudad: "Tunja", departamento: "Boyacá" },
  { ciudad: "Tununguá", departamento: "Boyacá" },
  { ciudad: "Turmequé", departamento: "Boyacá" },
  { ciudad: "Tuta", departamento: "Boyacá" },
  { ciudad: "Tutazá", departamento: "Boyacá" },
  { ciudad: "Umbita", departamento: "Boyacá" },
  { ciudad: "Ventaquemada", departamento: "Boyacá" },
  { ciudad: "Villa De Leyva", departamento: "Boyacá" },
  { ciudad: "Viracachá", departamento: "Boyacá" },
  { ciudad: "Zetaquira", departamento: "Boyacá" },
  { ciudad: "Aguadas", departamento: "Caldas" },
  { ciudad: "Anserma", departamento: "Caldas" },
  { ciudad: "Aranzazu", departamento: "Caldas" },
  { ciudad: "Belalcázar", departamento: "Caldas" },
  { ciudad: "Chinchina", departamento: "Caldas" },
  { ciudad: "Filadelfia", departamento: "Caldas" },
  { ciudad: "La Dorada", departamento: "Caldas" },
  { ciudad: "La Merced", departamento: "Caldas" },
  { ciudad: "Manizales", departamento: "Caldas" },
  { ciudad: "Manzanares", departamento: "Caldas" },
  { ciudad: "Marmato", departamento: "Caldas" },
  { ciudad: "Marquetalia", departamento: "Caldas" },
  { ciudad: "Marulanda", departamento: "Caldas" },
  { ciudad: "Neira", departamento: "Caldas" },
  { ciudad: "Norcasia", departamento: "Caldas" },
  { ciudad: "Pácora", departamento: "Caldas" },
  { ciudad: "Palestina", departamento: "Caldas" },
  { ciudad: "Pensilvania", departamento: "Caldas" },
  { ciudad: "Riosucio", departamento: "Caldas" },
  { ciudad: "Risaralda", departamento: "Caldas" },
  { ciudad: "Salamina", departamento: "Caldas" },
  { ciudad: "Samaná", departamento: "Caldas" },
  { ciudad: "San José", departamento: "Caldas" },
  { ciudad: "Supía", departamento: "Caldas" },
  { ciudad: "Victoria", departamento: "Caldas" },
  { ciudad: "Villamaria", departamento: "Caldas" },
  { ciudad: "Viterbo", departamento: "Caldas" },
  { ciudad: "Albania", departamento: "Caquetá" },
  { ciudad: "Belén De Los Andaquies", departamento: "Caquetá" },
  { ciudad: "Cartagena Del Chairá", departamento: "Caquetá" },
  { ciudad: "Currillo", departamento: "Caquetá" },
  { ciudad: "El Doncello", departamento: "Caquetá" },
  { ciudad: "El Paujil", departamento: "Caquetá" },
  { ciudad: "Florencia", departamento: "Caquetá" },
  { ciudad: "La Montañita", departamento: "Caquetá" },
  { ciudad: "Milan", departamento: "Caquetá" },
  { ciudad: "Morelia", departamento: "Caquetá" },
  { ciudad: "Puerto Rico", departamento: "Caquetá" },
  { ciudad: "San Jose Del Fragua", departamento: "Caquetá" },
  { ciudad: "San Vicente Del Caguán", departamento: "Caquetá" },
  { ciudad: "Solano", departamento: "Caquetá" },
  { ciudad: "Solita", departamento: "Caquetá" },
  { ciudad: "Valparaiso", departamento: "Caquetá" },
  { ciudad: "Aguazul", departamento: "Casanare" },
  { ciudad: "Chameza", departamento: "Casanare" },
  { ciudad: "Hato Corozal", departamento: "Casanare" },
  { ciudad: "La Salina", departamento: "Casanare" },
  { ciudad: "Maní", departamento: "Casanare" },
  { ciudad: "Monterrey", departamento: "Casanare" },
  { ciudad: "Nunchía", departamento: "Casanare" },
  { ciudad: "Orocué", departamento: "Casanare" },
  { ciudad: "Paz De Ariporo", departamento: "Casanare" },
  { ciudad: "Pore", departamento: "Casanare" },
  { ciudad: "Recetor", departamento: "Casanare" },
  { ciudad: "Sabanalarga", departamento: "Casanare" },
  { ciudad: "Sácama", departamento: "Casanare" },
  { ciudad: "San Luis De Palenque", departamento: "Casanare" },
  { ciudad: "Támara", departamento: "Casanare" },
  { ciudad: "Tauramena", departamento: "Casanare" },
  { ciudad: "Trinidad", departamento: "Casanare" },
  { ciudad: "Villanueva", departamento: "Casanare" },
  { ciudad: "Yopal", departamento: "Casanare" },
  { ciudad: "Almaguer", departamento: "Cauca" },
  { ciudad: "Argelia", departamento: "Cauca" },
  { ciudad: "Balboa", departamento: "Cauca" },
  { ciudad: "Bolívar", departamento: "Cauca" },
  { ciudad: "Buenos Aires", departamento: "Cauca" },
  { ciudad: "Cajibío", departamento: "Cauca" },
  { ciudad: "Caldono", departamento: "Cauca" },
  { ciudad: "Caloto", departamento: "Cauca" },
  { ciudad: "Corinto", departamento: "Cauca" },
  { ciudad: "El Tambo", departamento: "Cauca" },
  { ciudad: "Florencia", departamento: "Cauca" },
  { ciudad: "Guapi", departamento: "Cauca" },
  { ciudad: "Inzá", departamento: "Cauca" },
  { ciudad: "Jambalo", departamento: "Cauca" },
  { ciudad: "La Sierra", departamento: "Cauca" },
  { ciudad: "La Vega", departamento: "Cauca" },
  { ciudad: "Lopez", departamento: "Cauca" },
  { ciudad: "Mercaderes", departamento: "Cauca" },
  { ciudad: "Miranda", departamento: "Cauca" },
  { ciudad: "Morales", departamento: "Cauca" },
  { ciudad: "Padilla", departamento: "Cauca" },
  { ciudad: "Paez", departamento: "Cauca" },
  { ciudad: "Patia", departamento: "Cauca" },
  { ciudad: "Piamonte", departamento: "Cauca" },
  { ciudad: "Piendamo", departamento: "Cauca" },
  { ciudad: "Popayán", departamento: "Cauca" },
  { ciudad: "Puerto Tejada", departamento: "Cauca" },
  { ciudad: "Purace", departamento: "Cauca" },
  { ciudad: "Rosas", departamento: "Cauca" },
  { ciudad: "San Sebastian", departamento: "Cauca" },
  { ciudad: "Santa Rosa", departamento: "Cauca" },
  { ciudad: "Santander De Quilichao", departamento: "Cauca" },
  { ciudad: "Silvia", departamento: "Cauca" },
  { ciudad: "Sotara", departamento: "Cauca" },
  { ciudad: "Suarez", departamento: "Cauca" },
  { ciudad: "Sucre", departamento: "Cauca" },
  { ciudad: "Timbio", departamento: "Cauca" },
  { ciudad: "Timbiqui", departamento: "Cauca" },
  { ciudad: "Toribio", departamento: "Cauca" },
  { ciudad: "Totoro", departamento: "Cauca" },
  { ciudad: "Villa Rica", departamento: "Cauca" },
  { ciudad: "Aguachica", departamento: "Cesar" },
  { ciudad: "Agustín Codazzi", departamento: "Cesar" },
  { ciudad: "Astrea", departamento: "Cesar" },
  { ciudad: "Becerril", departamento: "Cesar" },
  { ciudad: "Bosconia", departamento: "Cesar" },
  { ciudad: "Chimichagua", departamento: "Cesar" },
  { ciudad: "Chiriguana", departamento: "Cesar" },
  { ciudad: "Curumaní", departamento: "Cesar" },
  { ciudad: "El Copey", departamento: "Cesar" },
  { ciudad: "El Paso", departamento: "Cesar" },
  { ciudad: "Gamarra", departamento: "Cesar" },
  { ciudad: "González", departamento: "Cesar" },
  { ciudad: "La Gloria", departamento: "Cesar" },
  { ciudad: "La Jagua De Ibirico", departamento: "Cesar" },
  { ciudad: "La Paz", departamento: "Cesar" },
  { ciudad: "Manaure", departamento: "Cesar" },
  { ciudad: "Pailitas", departamento: "Cesar" },
  { ciudad: "Pelaya", departamento: "Cesar" },
  { ciudad: "Pueblo Bello", departamento: "Cesar" },
  { ciudad: "Río De Oro", departamento: "Cesar" },
  { ciudad: "San Alberto", departamento: "Cesar" },
  { ciudad: "San Diego", departamento: "Cesar" },
  { ciudad: "San Martín", departamento: "Cesar" },
  { ciudad: "Tamalameque", departamento: "Cesar" },
  { ciudad: "Valledupar", departamento: "Cesar" },
  { ciudad: "Acandí", departamento: "Chocó" },
  { ciudad: "Alto Baudó", departamento: "Chocó" },
  { ciudad: "Atrato", departamento: "Chocó" },
  { ciudad: "Bagadó", departamento: "Chocó" },
  { ciudad: "Bahía Solano", departamento: "Chocó" },
  { ciudad: "Bajo Baudó", departamento: "Chocó" },
  { ciudad: "Belén De Bajira", departamento: "Chocó" },
  { ciudad: "Bojaya", departamento: "Chocó" },
  { ciudad: "Canton De San Pablo", departamento: "Chocó" },
  { ciudad: "Carmén Del Darién", departamento: "Chocó" },
  { ciudad: "Certegui", departamento: "Chocó" },
  { ciudad: "Condoto", departamento: "Chocó" },
  { ciudad: "El Carmen De Atrato", departamento: "Chocó" },
  { ciudad: "El Litoral Del San Juan", departamento: "Chocó" },
  { ciudad: "Itsmina", departamento: "Chocó" },
  { ciudad: "Juradó", departamento: "Chocó" },
  { ciudad: "Lloró", departamento: "Chocó" },
  { ciudad: "Medio Atrato", departamento: "Chocó" },
  { ciudad: "Medio Baudó", departamento: "Chocó" },
  { ciudad: "Medio San Juan", departamento: "Chocó" },
  { ciudad: "Nóvita", departamento: "Chocó" },
  { ciudad: "Nuquí", departamento: "Chocó" },
  { ciudad: "Quibdó", departamento: "Chocó" },
  { ciudad: "Río Frío", departamento: "Chocó" },
  { ciudad: "Rio Quito", departamento: "Chocó" },
  { ciudad: "Riosucio", departamento: "Chocó" },
  { ciudad: "San José Del Palmar", departamento: "Chocó" },
  { ciudad: "Sipí", departamento: "Chocó" },
  { ciudad: "Tadó", departamento: "Chocó" },
  { ciudad: "Unguía", departamento: "Chocó" },
  { ciudad: "Union Panamericana", departamento: "Chocó" },
  { ciudad: "Ayapel", departamento: "Córdoba" },
  { ciudad: "Buenavista", departamento: "Córdoba" },
  { ciudad: "Canalete", departamento: "Córdoba" },
  { ciudad: "Cereté", departamento: "Córdoba" },
  { ciudad: "Chimá", departamento: "Córdoba" },
  { ciudad: "Chinú", departamento: "Córdoba" },
  { ciudad: "Ciénaga De Oro", departamento: "Córdoba" },
  { ciudad: "Cotorra", departamento: "Córdoba" },
  { ciudad: "La Apartada", departamento: "Córdoba" },
  { ciudad: "Lorica", departamento: "Córdoba" },
  { ciudad: "Los Córdobas", departamento: "Córdoba" },
  { ciudad: "Momil", departamento: "Córdoba" },
  { ciudad: "Moñitos", departamento: "Córdoba" },
  { ciudad: "Montelíbano", departamento: "Córdoba" },
  { ciudad: "Montería", departamento: "Córdoba" },
  { ciudad: "Planeta Rica", departamento: "Córdoba" },
  { ciudad: "Pueblo Nuevo", departamento: "Córdoba" },
  { ciudad: "Puerto Escondido", departamento: "Córdoba" },
  { ciudad: "Puerto Libertador", departamento: "Córdoba" },
  { ciudad: "Purísima", departamento: "Córdoba" },
  { ciudad: "Sahagún", departamento: "Córdoba" },
  { ciudad: "San Andrés Sotavento", departamento: "Córdoba" },
  { ciudad: "San Antero", departamento: "Córdoba" },
  { ciudad: "San Bernardo Del Viento", departamento: "Córdoba" },
  { ciudad: "San Carlos", departamento: "Córdoba" },
  { ciudad: "San Pelayo", departamento: "Córdoba" },
  { ciudad: "Tierralta", departamento: "Córdoba" },
  { ciudad: "Valencia", departamento: "Córdoba" },
  { ciudad: "Agua De Dios", departamento: "Cundinamarca" },
  { ciudad: "Albán", departamento: "Cundinamarca" },
  { ciudad: "Anapoima", departamento: "Cundinamarca" },
  { ciudad: "Anolaima", departamento: "Cundinamarca" },
  { ciudad: "Apulo", departamento: "Cundinamarca" },
  { ciudad: "Arbeláez", departamento: "Cundinamarca" },
  { ciudad: "Beltrán", departamento: "Cundinamarca" },
  { ciudad: "Bituima", departamento: "Cundinamarca" },
  { ciudad: "Bojacá", departamento: "Cundinamarca" },
  { ciudad: "Cabrera", departamento: "Cundinamarca" },
  { ciudad: "Cachipay", departamento: "Cundinamarca" },
  { ciudad: "Cajicá", departamento: "Cundinamarca" },
  { ciudad: "Caparrapí", departamento: "Cundinamarca" },
  { ciudad: "Caqueza", departamento: "Cundinamarca" },
  { ciudad: "Carmen De Carupa", departamento: "Cundinamarca" },
  { ciudad: "Chaguaní", departamento: "Cundinamarca" },
  { ciudad: "Chía", departamento: "Cundinamarca" },
  { ciudad: "Chipaque", departamento: "Cundinamarca" },
  { ciudad: "Choachí", departamento: "Cundinamarca" },
  { ciudad: "Chocontá", departamento: "Cundinamarca" },
  { ciudad: "Cogua", departamento: "Cundinamarca" },
  { ciudad: "Cota", departamento: "Cundinamarca" },
  { ciudad: "Cucunubá", departamento: "Cundinamarca" },
  { ciudad: "El Colegio", departamento: "Cundinamarca" },
  { ciudad: "El Peñón", departamento: "Cundinamarca" },
  { ciudad: "El Rosal", departamento: "Cundinamarca" },
  { ciudad: "Facatativá", departamento: "Cundinamarca" },
  { ciudad: "Fomeque", departamento: "Cundinamarca" },
  { ciudad: "Fosca", departamento: "Cundinamarca" },
  { ciudad: "Funza", departamento: "Cundinamarca" },
  { ciudad: "Fúquene", departamento: "Cundinamarca" },
  { ciudad: "Fusagasugá", departamento: "Cundinamarca" },
  { ciudad: "Gachala", departamento: "Cundinamarca" },
  { ciudad: "Gachancipá", departamento: "Cundinamarca" },
  { ciudad: "Gacheta", departamento: "Cundinamarca" },
  { ciudad: "Gama", departamento: "Cundinamarca" },
  { ciudad: "Girardot", departamento: "Cundinamarca" },
  { ciudad: "Granada", departamento: "Cundinamarca" },
  { ciudad: "Guachetá", departamento: "Cundinamarca" },
  { ciudad: "Guaduas", departamento: "Cundinamarca" },
  { ciudad: "Guasca", departamento: "Cundinamarca" },
  { ciudad: "Guataquí", departamento: "Cundinamarca" },
  { ciudad: "Guatavita", departamento: "Cundinamarca" },
  { ciudad: "Guayabal De Siquima", departamento: "Cundinamarca" },
  { ciudad: "Guayabetal", departamento: "Cundinamarca" },
  { ciudad: "Gutiérrez", departamento: "Cundinamarca" },
  { ciudad: "Jerusalén", departamento: "Cundinamarca" },
  { ciudad: "Junín", departamento: "Cundinamarca" },
  { ciudad: "La Calera", departamento: "Cundinamarca" },
  { ciudad: "La Mesa", departamento: "Cundinamarca" },
  { ciudad: "La Palma", departamento: "Cundinamarca" },
  { ciudad: "La Peña", departamento: "Cundinamarca" },
  { ciudad: "La Vega", departamento: "Cundinamarca" },
  { ciudad: "Lenguazaque", departamento: "Cundinamarca" },
  { ciudad: "Macheta", departamento: "Cundinamarca" },
  { ciudad: "Madrid", departamento: "Cundinamarca" },
  { ciudad: "Manta", departamento: "Cundinamarca" },
  { ciudad: "Medina", departamento: "Cundinamarca" },
  { ciudad: "Mosquera", departamento: "Cundinamarca" },
  { ciudad: "Nariño", departamento: "Cundinamarca" },
  { ciudad: "Nemocon", departamento: "Cundinamarca" },
  { ciudad: "Nilo", departamento: "Cundinamarca" },
  { ciudad: "Nimaima", departamento: "Cundinamarca" },
  { ciudad: "Nocaima", departamento: "Cundinamarca" },
  { ciudad: "Pacho", departamento: "Cundinamarca" },
  { ciudad: "Paime", departamento: "Cundinamarca" },
  { ciudad: "Pandi", departamento: "Cundinamarca" },
  { ciudad: "Paratebueno", departamento: "Cundinamarca" },
  { ciudad: "Pasca", departamento: "Cundinamarca" },
  { ciudad: "Puerto Salgar", departamento: "Cundinamarca" },
  { ciudad: "Puli", departamento: "Cundinamarca" },
  { ciudad: "Quebradanegra", departamento: "Cundinamarca" },
  { ciudad: "Quetame", departamento: "Cundinamarca" },
  { ciudad: "Quipile", departamento: "Cundinamarca" },
  { ciudad: "Ricaurte", departamento: "Cundinamarca" },
  { ciudad: "San Antonio De Tequendama", departamento: "Cundinamarca" },
  { ciudad: "San Bernardo", departamento: "Cundinamarca" },
  { ciudad: "San Cayetano", departamento: "Cundinamarca" },
  { ciudad: "San Francisco", departamento: "Cundinamarca" },
  { ciudad: "San Juan De Río Seco", departamento: "Cundinamarca" },
  { ciudad: "Sasaima", departamento: "Cundinamarca" },
  { ciudad: "Sesquilé", departamento: "Cundinamarca" },
  { ciudad: "Sibaté", departamento: "Cundinamarca" },
  { ciudad: "Silvania", departamento: "Cundinamarca" },
  { ciudad: "Simijaca", departamento: "Cundinamarca" },
  { ciudad: "Soacha", departamento: "Cundinamarca" },
  { ciudad: "Sopó", departamento: "Cundinamarca" },
  { ciudad: "Subachoque", departamento: "Cundinamarca" },
  { ciudad: "Suesca", departamento: "Cundinamarca" },
  { ciudad: "Supatá", departamento: "Cundinamarca" },
  { ciudad: "Susa", departamento: "Cundinamarca" },
  { ciudad: "Sutatausa", departamento: "Cundinamarca" },
  { ciudad: "Tabio", departamento: "Cundinamarca" },
  { ciudad: "Tausa", departamento: "Cundinamarca" },
  { ciudad: "Tena", departamento: "Cundinamarca" },
  { ciudad: "Tenjo", departamento: "Cundinamarca" },
  { ciudad: "Tibacuy", departamento: "Cundinamarca" },
  { ciudad: "Tibirita", departamento: "Cundinamarca" },
  { ciudad: "Tocaima", departamento: "Cundinamarca" },
  { ciudad: "Tocancipá", departamento: "Cundinamarca" },
  { ciudad: "Topaipi", departamento: "Cundinamarca" },
  { ciudad: "Ubalá", departamento: "Cundinamarca" },
  { ciudad: "Ubaque", departamento: "Cundinamarca" },
  { ciudad: "Ubate", departamento: "Cundinamarca" },
  { ciudad: "Une", departamento: "Cundinamarca" },
  { ciudad: "Útica", departamento: "Cundinamarca" },
  { ciudad: "Venecia", departamento: "Cundinamarca" },
  { ciudad: "Vergara", departamento: "Cundinamarca" },
  { ciudad: "Vianí", departamento: "Cundinamarca" },
  { ciudad: "Villagomez", departamento: "Cundinamarca" },
  { ciudad: "Villapinzón", departamento: "Cundinamarca" },
  { ciudad: "Villeta", departamento: "Cundinamarca" },
  { ciudad: "Viotá", departamento: "Cundinamarca" },
  { ciudad: "Yacopí", departamento: "Cundinamarca" },
  { ciudad: "Zipacon", departamento: "Cundinamarca" },
  { ciudad: "Zipaquirá", departamento: "Cundinamarca" },
  { ciudad: "Barranco Mina", departamento: "Guainía" },
  { ciudad: "Cacahual", departamento: "Guainía" },
  { ciudad: "Inírida", departamento: "Guainía" },
  { ciudad: "La Guadalupe", departamento: "Guainía" },
  { ciudad: "Mapiripan", departamento: "Guainía" },
  { ciudad: "Morichal", departamento: "Guainía" },
  { ciudad: "Pana Pana", departamento: "Guainía" },
  { ciudad: "Puerto Colombia", departamento: "Guainía" },
  { ciudad: "San Felipe", departamento: "Guainía" },
  { ciudad: "Calamar", departamento: "Guaviare" },
  { ciudad: "El Retorno", departamento: "Guaviare" },
  { ciudad: "Miraflores", departamento: "Guaviare" },
  { ciudad: "San José Del Guaviare", departamento: "Guaviare" },
  { ciudad: "Acevedo", departamento: "Huila" },
  { ciudad: "Agrado", departamento: "Huila" },
  { ciudad: "Aipe", departamento: "Huila" },
  { ciudad: "Algeciras", departamento: "Huila" },
  { ciudad: "Altamira", departamento: "Huila" },
  { ciudad: "Baraya", departamento: "Huila" },
  { ciudad: "Campoalegre", departamento: "Huila" },
  { ciudad: "Colombia", departamento: "Huila" },
  { ciudad: "Elías", departamento: "Huila" },
  { ciudad: "Garzón", departamento: "Huila" },
  { ciudad: "Gigante", departamento: "Huila" },
  { ciudad: "Guadalupe", departamento: "Huila" },
  { ciudad: "Hobo", departamento: "Huila" },
  { ciudad: "Iquira", departamento: "Huila" },
  { ciudad: "Isnos", departamento: "Huila" },
  { ciudad: "La Argentina", departamento: "Huila" },
  { ciudad: "La Plata", departamento: "Huila" },
  { ciudad: "Nátaga", departamento: "Huila" },
  { ciudad: "Neiva", departamento: "Huila" },
  { ciudad: "Oporapa", departamento: "Huila" },
  { ciudad: "Paicol", departamento: "Huila" },
  { ciudad: "Palermo", departamento: "Huila" },
  { ciudad: "Palestina", departamento: "Huila" },
  { ciudad: "Pital", departamento: "Huila" },
  { ciudad: "Pitalito", departamento: "Huila" },
  { ciudad: "Rivera", departamento: "Huila" },
  { ciudad: "Saladoblanco", departamento: "Huila" },
  { ciudad: "San Agustín", departamento: "Huila" },
  { ciudad: "Santa María", departamento: "Huila" },
  { ciudad: "Suaza", departamento: "Huila" },
  { ciudad: "Tarqui", departamento: "Huila" },
  { ciudad: "Tello", departamento: "Huila" },
  { ciudad: "Teruel", departamento: "Huila" },
  { ciudad: "Tesalia", departamento: "Huila" },
  { ciudad: "Timaná", departamento: "Huila" },
  { ciudad: "Villavieja", departamento: "Huila" },
  { ciudad: "Yaguará", departamento: "Huila" },
  { ciudad: "Albania", departamento: "La Guajira" },
  { ciudad: "Barrancas", departamento: "La Guajira" },
  { ciudad: "Dibulla", departamento: "La Guajira" },
  { ciudad: "Distraccion", departamento: "La Guajira" },
  { ciudad: "El Molino", departamento: "La Guajira" },
  { ciudad: "Fonseca", departamento: "La Guajira" },
  { ciudad: "Hatonuevo", departamento: "La Guajira" },
  { ciudad: "La Jagua Del Pilar", departamento: "La Guajira" },
  { ciudad: "Maicao", departamento: "La Guajira" },
  { ciudad: "Manaure", departamento: "La Guajira" },
  { ciudad: "Riohacha", departamento: "La Guajira" },
  { ciudad: "San Juan Del Cesar", departamento: "La Guajira" },
  { ciudad: "Uribia", departamento: "La Guajira" },
  { ciudad: "Urumita", departamento: "La Guajira" },
  { ciudad: "Villanueva", departamento: "La Guajira" },
  { ciudad: "Algarrobo", departamento: "Magdalena" },
  { ciudad: "Aracataca", departamento: "Magdalena" },
  { ciudad: "Ariguaní", departamento: "Magdalena" },
  { ciudad: "Cerro San Antonio", departamento: "Magdalena" },
  { ciudad: "Chibolo", departamento: "Magdalena" },
  { ciudad: "Ciénaga", departamento: "Magdalena" },
  { ciudad: "Concordia", departamento: "Magdalena" },
  { ciudad: "El Banco", departamento: "Magdalena" },
  { ciudad: "El Piñon", departamento: "Magdalena" },
  { ciudad: "El Reten", departamento: "Magdalena" },
  { ciudad: "Fundacion", departamento: "Magdalena" },
  { ciudad: "Guamal", departamento: "Magdalena" },
  { ciudad: "Nueva Granada", departamento: "Magdalena" },
  { ciudad: "Pedraza", departamento: "Magdalena" },
  { ciudad: "Pijiño Del Carmen", departamento: "Magdalena" },
  { ciudad: "Pivijay", departamento: "Magdalena" },
  { ciudad: "Plato", departamento: "Magdalena" },
  { ciudad: "Pueblo Viejo", departamento: "Magdalena" },
  { ciudad: "Remolino", departamento: "Magdalena" },
  { ciudad: "Sabanas De San Angel", departamento: "Magdalena" },
  { ciudad: "Salamina", departamento: "Magdalena" },
  { ciudad: "San Sebastian De Buenavista", departamento: "Magdalena" },
  { ciudad: "San Zenon", departamento: "Magdalena" },
  { ciudad: "Santa Ana", departamento: "Magdalena" },
  { ciudad: "Santa Barbara De Pinto", departamento: "Magdalena" },
  { ciudad: "Santa Marta", departamento: "Magdalena" },
  { ciudad: "Sitionuevo", departamento: "Magdalena" },
  { ciudad: "Tenerife", departamento: "Magdalena" },
  { ciudad: "Zapayan", departamento: "Magdalena" },
  { ciudad: "Zona Bananera", departamento: "Magdalena" },
  { ciudad: "Acacias", departamento: "Meta" },
  { ciudad: "Barranca De Upia", departamento: "Meta" },
  { ciudad: "Cabuyaro", departamento: "Meta" },
  { ciudad: "Castilla La Nueva", departamento: "Meta" },
  { ciudad: "Cumaral", departamento: "Meta" },
  { ciudad: "El Calvario", departamento: "Meta" },
  { ciudad: "El Castillo", departamento: "Meta" },
  { ciudad: "El Dorado", departamento: "Meta" },
  { ciudad: "Fuente De Oro", departamento: "Meta" },
  { ciudad: "Granada", departamento: "Meta" },
  { ciudad: "Guamal", departamento: "Meta" },
  { ciudad: "La Macarena", departamento: "Meta" },
  { ciudad: "La Uribe", departamento: "Meta" },
  { ciudad: "Lejanías", departamento: "Meta" },
  { ciudad: "Mapiripan", departamento: "Meta" },
  { ciudad: "Mesetas", departamento: "Meta" },
  { ciudad: "Puerto Concordia", departamento: "Meta" },
  { ciudad: "Puerto Gaitán", departamento: "Meta" },
  { ciudad: "Puerto Lleras", departamento: "Meta" },
  { ciudad: "Puerto Lopez", departamento: "Meta" },
  { ciudad: "Puerto Rico", departamento: "Meta" },
  { ciudad: "Restrepo", departamento: "Meta" },
  { ciudad: "San Carlos Guaroa", departamento: "Meta" },
  { ciudad: "San Juan De Arama", departamento: "Meta" },
  { ciudad: "San Juanito", departamento: "Meta" },
  { ciudad: "San Luis De Cubarral", departamento: "Meta" },
  { ciudad: "San Martín", departamento: "Meta" },
  { ciudad: "Villavicencio", departamento: "Meta" },
  { ciudad: "Vista Hermosa", departamento: "Meta" },
  { ciudad: "Alban", departamento: "Nariño" },
  { ciudad: "Aldana", departamento: "Nariño" },
  { ciudad: "Ancuya", departamento: "Nariño" },
  { ciudad: "Arboleda", departamento: "Nariño" },
  { ciudad: "Barbacoas", departamento: "Nariño" },
  { ciudad: "Belen", departamento: "Nariño" },
  { ciudad: "Buesaco", departamento: "Nariño" },
  { ciudad: "Chachagui", departamento: "Nariño" },
  { ciudad: "Colon", departamento: "Nariño" },
  { ciudad: "Consaca", departamento: "Nariño" },
  { ciudad: "Contadero", departamento: "Nariño" },
  { ciudad: "Córdoba", departamento: "Nariño" },
  { ciudad: "Cuaspud", departamento: "Nariño" },
  { ciudad: "Cumbal", departamento: "Nariño" },
  { ciudad: "Cumbitara", departamento: "Nariño" },
  { ciudad: "El Charco", departamento: "Nariño" },
  { ciudad: "El Peñol", departamento: "Nariño" },
  { ciudad: "El Rosario", departamento: "Nariño" },
  { ciudad: "El Tablon De Gomez", departamento: "Nariño" },
  { ciudad: "El Tambo", departamento: "Nariño" },
  { ciudad: "Francisco Pizarro", departamento: "Nariño" },
  { ciudad: "Funes", departamento: "Nariño" },
  { ciudad: "Guachucal", departamento: "Nariño" },
  { ciudad: "Guaitarilla", departamento: "Nariño" },
  { ciudad: "Gualmatan", departamento: "Nariño" },
  { ciudad: "Iles", departamento: "Nariño" },
  { ciudad: "Imues", departamento: "Nariño" },
  { ciudad: "Ipiales", departamento: "Nariño" },
  { ciudad: "La Cruz", departamento: "Nariño" },
  { ciudad: "La Florida", departamento: "Nariño" },
  { ciudad: "La Llanada", departamento: "Nariño" },
  { ciudad: "La Tola", departamento: "Nariño" },
  { ciudad: "La Union", departamento: "Nariño" },
  { ciudad: "Leiva", departamento: "Nariño" },
  { ciudad: "Linares", departamento: "Nariño" },
  { ciudad: "Los Andes", departamento: "Nariño" },
  { ciudad: "Magui", departamento: "Nariño" },
  { ciudad: "Mallama", departamento: "Nariño" },
  { ciudad: "Mosquera", departamento: "Nariño" },
  { ciudad: "Nariño", departamento: "Nariño" },
  { ciudad: "Olaya Herrera", departamento: "Nariño" },
  { ciudad: "Ospina", departamento: "Nariño" },
  { ciudad: "Pasto", departamento: "Nariño" },
  { ciudad: "Policarpa", departamento: "Nariño" },
  { ciudad: "Potosí", departamento: "Nariño" },
  { ciudad: "Providencia", departamento: "Nariño" },
  { ciudad: "Puerres", departamento: "Nariño" },
  { ciudad: "Pupiales", departamento: "Nariño" },
  { ciudad: "Ricaurte", departamento: "Nariño" },
  { ciudad: "Roberto Payan", departamento: "Nariño" },
  { ciudad: "Samaniego", departamento: "Nariño" },
  { ciudad: "San Bernardo", departamento: "Nariño" },
  { ciudad: "San Lorenzo", departamento: "Nariño" },
  { ciudad: "San Pablo", departamento: "Nariño" },
  { ciudad: "San Pedro De Cartago", departamento: "Nariño" },
  { ciudad: "Sandoná", departamento: "Nariño" },
  { ciudad: "Santa Barbara", departamento: "Nariño" },
  { ciudad: "Santa Cruz", departamento: "Nariño" },
  { ciudad: "Sapuyes", departamento: "Nariño" },
  { ciudad: "Taminango", departamento: "Nariño" },
  { ciudad: "Tangua", departamento: "Nariño" },
  { ciudad: "Tumaco", departamento: "Nariño" },
  { ciudad: "Tuquerres", departamento: "Nariño" },
  { ciudad: "Yacuanquer", departamento: "Nariño" },
  { ciudad: "Abrego", departamento: "Norte de Santander" },
  { ciudad: "Arboledas", departamento: "Norte de Santander" },
  { ciudad: "Bochalema", departamento: "Norte de Santander" },
  { ciudad: "Bucarasica", departamento: "Norte de Santander" },
  { ciudad: "Cachirá", departamento: "Norte de Santander" },
  { ciudad: "Cácota", departamento: "Norte de Santander" },
  { ciudad: "Chinácota", departamento: "Norte de Santander" },
  { ciudad: "Chitagá", departamento: "Norte de Santander" },
  { ciudad: "Convención", departamento: "Norte de Santander" },
  { ciudad: "Cúcuta", departamento: "Norte de Santander" },
  { ciudad: "Cucutilla", departamento: "Norte de Santander" },
  { ciudad: "Durania", departamento: "Norte de Santander" },
  { ciudad: "El Carmen", departamento: "Norte de Santander" },
  { ciudad: "El Tarra", departamento: "Norte de Santander" },
  { ciudad: "El Zulia", departamento: "Norte de Santander" },
  { ciudad: "Gramalote", departamento: "Norte de Santander" },
  { ciudad: "Hacarí", departamento: "Norte de Santander" },
  { ciudad: "Herrán", departamento: "Norte de Santander" },
  { ciudad: "La Esperanza", departamento: "Norte de Santander" },
  { ciudad: "La Playa", departamento: "Norte de Santander" },
  { ciudad: "Labateca", departamento: "Norte de Santander" },
  { ciudad: "Los Patios", departamento: "Norte de Santander" },
  { ciudad: "Lourdes", departamento: "Norte de Santander" },
  { ciudad: "Mutiscua", departamento: "Norte de Santander" },
  { ciudad: "Ocaña", departamento: "Norte de Santander" },
  { ciudad: "Pamplona", departamento: "Norte de Santander" },
  { ciudad: "Pamplonita", departamento: "Norte de Santander" },
  { ciudad: "Puerto Santander", departamento: "Norte de Santander" },
  { ciudad: "Ragonvalia", departamento: "Norte de Santander" },
  { ciudad: "Salazar", departamento: "Norte de Santander" },
  { ciudad: "San Calixto", departamento: "Norte de Santander" },
  { ciudad: "San Cayetano", departamento: "Norte de Santander" },
  { ciudad: "Santiago", departamento: "Norte de Santander" },
  { ciudad: "Sardinata", departamento: "Norte de Santander" },
  { ciudad: "Silos", departamento: "Norte de Santander" },
  { ciudad: "Teorama", departamento: "Norte de Santander" },
  { ciudad: "Tibú", departamento: "Norte de Santander" },
  { ciudad: "Toledo", departamento: "Norte de Santander" },
  { ciudad: "Villa Caro", departamento: "Norte de Santander" },
  { ciudad: "Villa Del Rosario", departamento: "Norte de Santander" },
  { ciudad: "Colón", departamento: "Putumayo" },
  { ciudad: "Mocoa", departamento: "Putumayo" },
  { ciudad: "Orito", departamento: "Putumayo" },
  { ciudad: "Puerto Asis", departamento: "Putumayo" },
  { ciudad: "Puerto Caicedo", departamento: "Putumayo" },
  { ciudad: "Puerto Guzman", departamento: "Putumayo" },
  { ciudad: "Puerto Leguizamo", departamento: "Putumayo" },
  { ciudad: "San Francisco", departamento: "Putumayo" },
  { ciudad: "San Miguel", departamento: "Putumayo" },
  { ciudad: "Santiago", departamento: "Putumayo" },
  { ciudad: "Sibundoy", departamento: "Putumayo" },
  { ciudad: "Valle Del Guamuez", departamento: "Putumayo" },
  { ciudad: "Villa Garzon", departamento: "Putumayo" },
  { ciudad: "Armenia", departamento: "Quindío" },
  { ciudad: "Buenavista", departamento: "Quindío" },
  { ciudad: "Calarca", departamento: "Quindío" },
  { ciudad: "Circasia", departamento: "Quindío" },
  { ciudad: "Cordoba", departamento: "Quindío" },
  { ciudad: "Filandia", departamento: "Quindío" },
  { ciudad: "Genova", departamento: "Quindío" },
  { ciudad: "La Tebaida", departamento: "Quindío" },
  { ciudad: "Montengro", departamento: "Quindío" },
  { ciudad: "Pijao", departamento: "Quindío" },
  { ciudad: "Quimbaya", departamento: "Quindío" },
  { ciudad: "Salento", departamento: "Quindío" },
  { ciudad: "Apía", departamento: "Risaralda" },
  { ciudad: "Balboa", departamento: "Risaralda" },
  { ciudad: "Belén De Umbría", departamento: "Risaralda" },
  { ciudad: "Dosquebradas", departamento: "Risaralda" },
  { ciudad: "Guática", departamento: "Risaralda" },
  { ciudad: "La Celia", departamento: "Risaralda" },
  { ciudad: "La Virginia", departamento: "Risaralda" },
  { ciudad: "Marsella", departamento: "Risaralda" },
  { ciudad: "Mistrató", departamento: "Risaralda" },
  { ciudad: "Pereira", departamento: "Risaralda" },
  { ciudad: "Pueblo Rico", departamento: "Risaralda" },
  { ciudad: "Quinchia", departamento: "Risaralda" },
  { ciudad: "Santa Rosa De Cabal", departamento: "Risaralda" },
  { ciudad: "Santuario", departamento: "Risaralda" },
  { ciudad: "Aguada", departamento: "Santander" },
  { ciudad: "Albania", departamento: "Santander" },
  { ciudad: "Aratoca", departamento: "Santander" },
  { ciudad: "Barbosa", departamento: "Santander" },
  { ciudad: "Barichara", departamento: "Santander" },
  { ciudad: "Barrancabermeja", departamento: "Santander" },
  { ciudad: "Betulia", departamento: "Santander" },
  { ciudad: "Bolívar", departamento: "Santander" },
  { ciudad: "Bucaramanga", departamento: "Santander" },
  { ciudad: "Cabrera", departamento: "Santander" },
  { ciudad: "California", departamento: "Santander" },
  { ciudad: "Capitanejo", departamento: "Santander" },
  { ciudad: "Carcasí", departamento: "Santander" },
  { ciudad: "Cepitá", departamento: "Santander" },
  { ciudad: "Cerrito", departamento: "Santander" },
  { ciudad: "Charalá", departamento: "Santander" },
  { ciudad: "Charta", departamento: "Santander" },
  { ciudad: "Chima", departamento: "Santander" },
  { ciudad: "Chipatá", departamento: "Santander" },
  { ciudad: "Cimitarra", departamento: "Santander" },
  { ciudad: "Concepción", departamento: "Santander" },
  { ciudad: "Confines", departamento: "Santander" },
  { ciudad: "Contratación", departamento: "Santander" },
  { ciudad: "Coromoro", departamento: "Santander" },
  { ciudad: "Curití", departamento: "Santander" },
  { ciudad: "El Carmen De Chucurí", departamento: "Santander" },
  { ciudad: "El Guacamayo", departamento: "Santander" },
  { ciudad: "El Peñón", departamento: "Santander" },
  { ciudad: "El Playón", departamento: "Santander" },
  { ciudad: "Encino", departamento: "Santander" },
  { ciudad: "Enciso", departamento: "Santander" },
  { ciudad: "Florián", departamento: "Santander" },
  { ciudad: "Floridablanca", departamento: "Santander" },
  { ciudad: "Galán", departamento: "Santander" },
  { ciudad: "Gambita", departamento: "Santander" },
  { ciudad: "Girón", departamento: "Santander" },
  { ciudad: "Guaca", departamento: "Santander" },
  { ciudad: "Guadalupe", departamento: "Santander" },
  { ciudad: "Guapotá", departamento: "Santander" },
  { ciudad: "Guavatá", departamento: "Santander" },
  { ciudad: "Guepsa", departamento: "Santander" },
  { ciudad: "Hato", departamento: "Santander" },
  { ciudad: "Jesús María", departamento: "Santander" },
  { ciudad: "Jordán", departamento: "Santander" },
  { ciudad: "La Belleza", departamento: "Santander" },
  { ciudad: "La Paz", departamento: "Santander" },
  { ciudad: "Landázuri", departamento: "Santander" },
  { ciudad: "Lebríja", departamento: "Santander" },
  { ciudad: "Los Santos", departamento: "Santander" },
  { ciudad: "Macaravita", departamento: "Santander" },
  { ciudad: "Málaga", departamento: "Santander" },
  { ciudad: "Matanza", departamento: "Santander" },
  { ciudad: "Mogotes", departamento: "Santander" },
  { ciudad: "Molagavita", departamento: "Santander" },
  { ciudad: "Ocamonte", departamento: "Santander" },
  { ciudad: "Oiba", departamento: "Santander" },
  { ciudad: "Onzaga", departamento: "Santander" },
  { ciudad: "Palmar", departamento: "Santander" },
  { ciudad: "Palmas Del Socorro", departamento: "Santander" },
  { ciudad: "Páramo", departamento: "Santander" },
  { ciudad: "Piedecuesta", departamento: "Santander" },
  { ciudad: "Pinchote", departamento: "Santander" },
  { ciudad: "Puente Nacional", departamento: "Santander" },
  { ciudad: "Puerto Parra", departamento: "Santander" },
  { ciudad: "Puerto Wilches", departamento: "Santander" },
  { ciudad: "Rionegro", departamento: "Santander" },
  { ciudad: "Sabana De Torres", departamento: "Santander" },
  { ciudad: "San Andrés", departamento: "Santander" },
  { ciudad: "San Benito", departamento: "Santander" },
  { ciudad: "San Gil", departamento: "Santander" },
  { ciudad: "San Joaquín", departamento: "Santander" },
  { ciudad: "San José De Miranda", departamento: "Santander" },
  { ciudad: "San Miguel", departamento: "Santander" },
  { ciudad: "San Vicente De Chucurí", departamento: "Santander" },
  { ciudad: "Santa Bárbara", departamento: "Santander" },
  { ciudad: "Santa Helena Del Opón", departamento: "Santander" },
  { ciudad: "Simacota", departamento: "Santander" },
  { ciudad: "Socorro", departamento: "Santander" },
  { ciudad: "Suaita", departamento: "Santander" },
  { ciudad: "Sucre", departamento: "Santander" },
  { ciudad: "Surata", departamento: "Santander" },
  { ciudad: "Tona", departamento: "Santander" },
  { ciudad: "Valle De San José", departamento: "Santander" },
  { ciudad: "Vélez", departamento: "Santander" },
  { ciudad: "Vetas", departamento: "Santander" },
  { ciudad: "Villanueva", departamento: "Santander" },
  { ciudad: "Zapatoca", departamento: "Santander" },
  { ciudad: "Buenavista", departamento: "Sucre" },
  { ciudad: "Caimito", departamento: "Sucre" },
  { ciudad: "Chalán", departamento: "Sucre" },
  { ciudad: "Coloso", departamento: "Sucre" },
  { ciudad: "Corozal", departamento: "Sucre" },
  { ciudad: "Coveñas", departamento: "Sucre" },
  { ciudad: "El Roble", departamento: "Sucre" },
  { ciudad: "Galeras", departamento: "Sucre" },
  { ciudad: "Guaranda", departamento: "Sucre" },
  { ciudad: "La Unión", departamento: "Sucre" },
  { ciudad: "Los Palmitos", departamento: "Sucre" },
  { ciudad: "Majagual", departamento: "Sucre" },
  { ciudad: "Morroa", departamento: "Sucre" },
  { ciudad: "Ovejas", departamento: "Sucre" },
  { ciudad: "Palmito", departamento: "Sucre" },
  { ciudad: "Sampués", departamento: "Sucre" },
  { ciudad: "San Benito Abad", departamento: "Sucre" },
  { ciudad: "San Juan Betulia", departamento: "Sucre" },
  { ciudad: "San Marcos", departamento: "Sucre" },
  { ciudad: "San Onofre", departamento: "Sucre" },
  { ciudad: "San Pedro", departamento: "Sucre" },
  { ciudad: "Santiago De Tolú", departamento: "Sucre" },
  { ciudad: "Sincé", departamento: "Sucre" },
  { ciudad: "Sincelejo", departamento: "Sucre" },
  { ciudad: "Sucre", departamento: "Sucre" },
  { ciudad: "Tolú Viejo", departamento: "Sucre" },
  { ciudad: "Alpujarra", departamento: "Tolima" },
  { ciudad: "Alvarado", departamento: "Tolima" },
  { ciudad: "Ambalema", departamento: "Tolima" },
  { ciudad: "Anzoátegui", departamento: "Tolima" },
  { ciudad: "Armero", departamento: "Tolima" },
  { ciudad: "Ataco", departamento: "Tolima" },
  { ciudad: "Cajamarca", departamento: "Tolima" },
  { ciudad: "Carmen De Apicalá", departamento: "Tolima" },
  { ciudad: "Casabianca", departamento: "Tolima" },
  { ciudad: "Chaparral", departamento: "Tolima" },
  { ciudad: "Coello", departamento: "Tolima" },
  { ciudad: "Coyaima", departamento: "Tolima" },
  { ciudad: "Cunday", departamento: "Tolima" },
  { ciudad: "Dolores", departamento: "Tolima" },
  { ciudad: "Espinal", departamento: "Tolima" },
  { ciudad: "Falan", departamento: "Tolima" },
  { ciudad: "Flandes", departamento: "Tolima" },
  { ciudad: "Fresno", departamento: "Tolima" },
  { ciudad: "Guamo", departamento: "Tolima" },
  { ciudad: "Herveo", departamento: "Tolima" },
  { ciudad: "Honda", departamento: "Tolima" },
  { ciudad: "Ibague", departamento: "Tolima" },
  { ciudad: "Icononzo", departamento: "Tolima" },
  { ciudad: "Lerida", departamento: "Tolima" },
  { ciudad: "Libano", departamento: "Tolima" },
  { ciudad: "Mariquita", departamento: "Tolima" },
  { ciudad: "Melgar", departamento: "Tolima" },
  { ciudad: "Murillo", departamento: "Tolima" },
  { ciudad: "Natagaima", departamento: "Tolima" },
  { ciudad: "Ortega", departamento: "Tolima" },
  { ciudad: "Palocabildo", departamento: "Tolima" },
  { ciudad: "Piedras", departamento: "Tolima" },
  { ciudad: "Planadas", departamento: "Tolima" },
  { ciudad: "Prado", departamento: "Tolima" },
  { ciudad: "Purificación", departamento: "Tolima" },
  { ciudad: "Rioblanco", departamento: "Tolima" },
  { ciudad: "Roncesvalles", departamento: "Tolima" },
  { ciudad: "Rovira", departamento: "Tolima" },
  { ciudad: "Saldaña", departamento: "Tolima" },
  { ciudad: "San Antonio", departamento: "Tolima" },
  { ciudad: "San Luis", departamento: "Tolima" },
  { ciudad: "Santa Isabel", departamento: "Tolima" },
  { ciudad: "Suárez", departamento: "Tolima" },
  { ciudad: "Valle De San Juan", departamento: "Tolima" },
  { ciudad: "Venadillo", departamento: "Tolima" },
  { ciudad: "Villahermosa", departamento: "Tolima" },
  { ciudad: "Villarrica", departamento: "Tolima" },
  { ciudad: "Alcala", departamento: "Valle del Cauca" },
  { ciudad: "Andalucía", departamento: "Valle del Cauca" },
  { ciudad: "Ansermanuevo", departamento: "Valle del Cauca" },
  { ciudad: "Argelia", departamento: "Valle del Cauca" },
  { ciudad: "Bolívar", departamento: "Valle del Cauca" },
  { ciudad: "Buenaventura", departamento: "Valle del Cauca" },
  { ciudad: "Buga", departamento: "Valle del Cauca" },
  { ciudad: "Bugalagrande", departamento: "Valle del Cauca" },
  { ciudad: "Caicedonia", departamento: "Valle del Cauca" },
  { ciudad: "Cali", departamento: "Valle del Cauca" },
  { ciudad: "Calima", departamento: "Valle del Cauca" },
  { ciudad: "Candelaria", departamento: "Valle del Cauca" },
  { ciudad: "Cartago", departamento: "Valle del Cauca" },
  { ciudad: "Dagua", departamento: "Valle del Cauca" },
  { ciudad: "El Águila", departamento: "Valle del Cauca" },
  { ciudad: "El Cairo", departamento: "Valle del Cauca" },
  { ciudad: "El Cerrito", departamento: "Valle del Cauca" },
  { ciudad: "El Dovio", departamento: "Valle del Cauca" },
  { ciudad: "Florida", departamento: "Valle del Cauca" },
  { ciudad: "Ginebra", departamento: "Valle del Cauca" },
  { ciudad: "Guacarí", departamento: "Valle del Cauca" },
  { ciudad: "Jamundí", departamento: "Valle del Cauca" },
  { ciudad: "La Cumbre", departamento: "Valle del Cauca" },
  { ciudad: "La Unión", departamento: "Valle del Cauca" },
  { ciudad: "La Victoria", departamento: "Valle del Cauca" },
  { ciudad: "Obando", departamento: "Valle del Cauca" },
  { ciudad: "Palmira", departamento: "Valle del Cauca" },
  { ciudad: "Pradera", departamento: "Valle del Cauca" },
  { ciudad: "Restrepo", departamento: "Valle del Cauca" },
  { ciudad: "Riofrio", departamento: "Valle del Cauca" },
  { ciudad: "Roldanillo", departamento: "Valle del Cauca" },
  { ciudad: "San Pedro", departamento: "Valle del Cauca" },
  { ciudad: "Sevilla", departamento: "Valle del Cauca" },
  { ciudad: "Toro", departamento: "Valle del Cauca" },
  { ciudad: "Trujillo", departamento: "Valle del Cauca" },
  { ciudad: "Tuluá", departamento: "Valle del Cauca" },
  { ciudad: "Ulloa", departamento: "Valle del Cauca" },
  { ciudad: "Versalles", departamento: "Valle del Cauca" },
  { ciudad: "Vijes", departamento: "Valle del Cauca" },
  { ciudad: "Yotoco", departamento: "Valle del Cauca" },
  { ciudad: "Yumbo", departamento: "Valle del Cauca" },
  { ciudad: "Zarzal", departamento: "Valle del Cauca" },
  { ciudad: "Caruru", departamento: "Vaupés" },
  { ciudad: "Mitú", departamento: "Vaupés" },
  { ciudad: "Pacoa", departamento: "Vaupés" },
  { ciudad: "Papunahua", departamento: "Vaupés" },
  { ciudad: "Taraira", departamento: "Vaupés" },
  { ciudad: "Yavaraté", departamento: "Vaupés" },
  { ciudad: "Cumaribo", departamento: "Vichada" },
  { ciudad: "La Primavera", departamento: "Vichada" },
  { ciudad: "Puerto Carreño", departamento: "Vichada" },
  { ciudad: "Santa Rosalía", departamento: "Vichada" },
];

export function searchCiudades(query: string, limit = 8): CiudadEntry[] {
  if (!query || query.length < 2) return [];
  const q = query.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
  return CIUDADES
    .filter((c) => {
      const ciudad = c.ciudad.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
      const depto = c.departamento.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "");
      return ciudad.includes(q) || depto.includes(q);
    })
    .slice(0, limit);
}
